version: "3.9"
services:
  dev:
    build:
      target: dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./htdocs
        target: /smrs/htdocs
      - type: bind
        source: ./conf
        target: /smrs/conf
      - type: bind
        source: ./data
        target: /smrs/data

  prod:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./data
        target: /smrs/data
