
[tasks.ensure-musl]
command = "rustup"
args = ["target", "add", "x86_64-unknown-linux-musl"]

[tasks.alpine-build]
dependencies = ["ensure-musl"]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-musl"]

[tasks.devenv]
command = "docker"
args = ["compose", "up", "dev", "-d"]

[tasks.devenv-shell]
script = "docker exec -ti smrs-httpd-1 /bin/sh"

[tasks.iter]
dependencies = ["alpine-build", "devenv"]
script = [
  "cp target/x86_64-unknown-linux-musl/debug/smrs htdocs/smrs.cgi"
]
